### ISSUE TITLE
[Question] How to use together with rc

### ISSUE THREAD

**Issue by Kikobeats** [snowyu/load-config-file.js#1]
I love this project; I was thinking about write a tiny module for try to load JSON/CSON/YAML file but not necessary because this project exists! kudos ❤️ .

About this aspect, how I can use it together with [rc](https://github.com/dominictarr/rc)?

Basically expose an API where you specify the parse for your files. For example, here, I use `CSON.parse`:

``` js
var rc = require('rc')
var conf = rc('myProject', DEFAULT.scaffold(), CSON.parse);
```

In the `CSON.parse` I want to use `load-config-file`. Can you give any guideline about how to use it?

**Comment by Kikobeats** [comment]
Another thing, I'm trying to load a file without format, could it be possible?

**Comment by snowyu** [comment]
1. Sorry, I have not used the `rc` package.  But the `load-config-file` should be a low-level library for rc.
   then you should ask the author of the `rc` package, about howto customize it to load.
2. That is easy, just write your own parser to load:
   
   ``` js
   function passContent(content){return content};
   loadConfig.register('.bin', passContent); // load a file without format.
   ```
